import Banner from "../components/Banner";
import Case from "../components/Case";
import CaseCard from "../components/CaseCard";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Head from "next/head";
import Link from "next/link";

function CaseStudy() {
  return (
    <>
      <Head>
        <title>MegaStack</title>
        <meta name="megastack app" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className=" bg-[url('/glass.png')] bg-no-repeat bg-cover flex flex-col items-center w-full h-full  pt-24 gap-24 mb-8 md:gap-32 md:pt-32 xl:pt-36 xl:gap-40 px-6 md:px-22 xl:py-6 xl:px-32">
        <div className=" flex flex-col items-center justify-center text-center mb-8 w-full mt-12  md:px-22 xl:px-26 gap-8">
          <h1 className=" flex items-center font-bold text-3xl md:text-5xl text-center tracking-wide xl:text-7xl  text-megaStackSecondary xl:px-48">
            Check out some of our partner’s projects
          </h1>
          <p className=" font-light text-xl md:text-1xl xl:text-2xl  text-center md:28 xl:px-36 ">
            We have collaborated on a variety of projects across divers
            industries and discipline. Yes, we make complex idea into usable,
            functional digital products and help our partners reach their goals
          </p>
          <Link href="/contact-us">
            <a>
              <button className=" bg-megaStackPrimaryBlueBase w-40 h-15 rounded-lg py-5 px-10 font-semibold text-white text-base">
                Lets Talk
              </button>
            </a>
          </Link>
        </div>
        {/* <div className=" flex flex-col md:flex-row xl:flex-row gap-4 md:gap-4 xl:gap-8 ">
          <div className=" flex flex-col gap-2 ">
            <h3 className=" text-megaStackNeutralblack font-semibold text-xl md:text-1xl xl:text-2xl ">
              We Ideate
            </h3>
            <p className=" font-light text-base xl:text-xl ">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget
              nullam erat quam tellus feugiat risus semper. Amet orci facilisi
              nec.
            </p>
          </div>
          <div className=" flex flex-col gap-2">
            <h3 className=" text-megaStackNeutralblack font-semibold text-xl md:text-1xl xl:text-2xl ">
              We Design
            </h3>
            <p className=" font-light text-base xl:text-xl  ">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget
              nullam erat quam tellus feugiat risus semper. Amet orci facilisi
              nec.
            </p>
          </div>
          <div className=" flex flex-col gap-2">
            <h3 className=" text-megaStackNeutralblack font-semibold text-xl md:text-1xl xl:text-2xl ">
              We Develop
            </h3>
            <p className=" font-light text-base xl:text-xl  ">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget
              nullam erat quam tellus feugiat risus semper. Amet orci facilisi
              nec.
            </p>
          </div>
        </div> */}
      </div>
      <Case />
      <div className=" px-6 md:px-22 xl:px-32 w-full">
        <div className=" flex flex-col xl:flex-row xl:flex-wrap md:flex-row md:flex-wrap gap-16 xl:gap-32 w-full">
          <CaseCard
            img={"/images/mockup.png"}
            study={"Yummy Spot"}
            aboutStudy={"UI/UX Design, Desktop App"}
          />
          <CaseCard
            img={"/images/mockup.png"}
            study={"Yummy Spot"}
            aboutStudy={"UI/UX Design, Desktop App"}
          />
        </div>
      </div>
      <Footer />
    </>
  );
}

export default CaseStudy;
